[Install]
; Options: Folder, Registry
Startup=Registry
DisabledHotkeys=CFKMWZ
EnableHexNumpad=1
Launch_App1=firefox.exe
Launch_App2=thunderbird.exe

[Clipboard]
MAX_FILE_AGE=3600

[Delay]
CLIP=100
KEY=100

[Log]
MAX_BUFFER_COUNT=256

[Path]
EDITOR=notepad++.exe -ro "{}"
TERMINAL=wtai.exe
MAX_DEPTH=1
MAX_SUBMENU=9
PAGE_SIZE=5

[Url]
BROWSER=firefox.exe -osint -url "{}"
PAGE_SIZE=20
