[Install]
; Installs AutoHotkey scripts and settings based on these values.
Startup=Registry
; Startup mode:
; "Folder":   creates a shortcut in the Startup folder.
; "Registry": adds an entry to the Windows Run registry key.
DisabledHotkeys=CFKMWZ
; Hex string of hotkeys to disable (e.g., CFKMWZ).
; Written to "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" with "DisabledHotkeys" value.
EnableHexNumpad=1
; Enables hex numpad input method.
; Written to "HKCU\Control Panel\Input Method" with "EnableHexNumpad" value.
Launch_App1=firefox.exe
; Path to the first launch application.
; If set, writes the path to "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AppKey\17" with "ShellExecute" value.
; If empty, removes registry entry.
Launch_App2=thunderbird.exe
; Path to the second launch application.
; If set, writes the path to "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AppKey\18" with "ShellExecute" value.
; If empty, removes registry entry.

[Clipboard]
; Clipboard monitoring settings.
ENABLED=0
; 0 = Disabled (no clipboard monitoring)
; 1 = Enabled (monitors clipboard changes)
MAX_FILE_AGE=3600
; Maximum age (in seconds) of clipboard files before automatic deletion.
; Files older than this will be deleted from A_Temp directory.

[Delay]
CLIP=100
; Delay in milliseconds before processing clipboard changes.
KEY=100
; Delay in milliseconds before sending input after pasting.

[Log]
; Maximum number of log entries stored in memory before flushing to log file.
; Controls buffer size for Log_Trace() function
MAX_BUFFER_COUNT=256

[Path]
EDITOR=notepad++.exe -ro "{}"
; Default text editor.
TERMINAL=wtai.exe
; Default terminal emulator.
MAX_DEPTH=1
; Maximum depth of nested menus.
; Limits the number of levels in context menus.
MAX_SUBMENU=9
; Maximum number of items per submenu.
; Limits the number of items displayed in context menus.
PAGE_SIZE=5
; Maximum number of items per page in dialogs.

[Url]
BROWSER=firefox.exe -osint -url "{}"
; Default web browser for URL handling.
PAGE_SIZE=20
; Maximum number of items per page in dialogs.
